version: '3'
services:
  postgres:
    image: postgres
    expose:
      - 5432
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: redis
    expose:
      - 6379
  news:
    links:
      - redis
      - postgres
    volumes:
      - ./:/news
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_REV
        - COMMIT_DATE
    environment:
      - REDIS_URL=redis://redis
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/newz
    ports:
      - 8080
volumes:
  pg-data:
    driver: local
